name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  check-api:
    name: Lint, format, and typecheck (API)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - uses: denoland/setup-deno@v2
      - name: Install dependencies (API)
        run: uv sync --directory api --dev
      - name: Install dependencies (web)
        run: deno install
        working-directory: web
      - uses: pre-commit/action@v3.0.1

  check-web:
    name: Lint, format, and typecheck (web)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - name: Install dependencies
        run: deno install
        working-directory: web
      - name: Check
        run: deno task check
        working-directory: web
